language: node_js
node_js:
	- "6"
	- "6.1"
	- "6.2"
	- "5"
	- "4"
	- "iojs"
before_script:
	- mkdir -p src/config
	- curl https://raw.githubusercontent.com/elasim/seanote/test/server.config.json > ./src/config/server.config.json
sudo: false
